<template>
      <div class="bg-white shadow-2xl rounded-2xl ml-2 custom-height w-96 lg:h-custom-height lg:w-custom-width justify-center">
      <div class="p-10">
        <h1 class="text-center text-2xl">Active contracts/Purchase Orders</h1>
      </div>
              <div class="break-words pl-5 pr-5 flex flex-col">
<table v-if="data" class="table-fixed text-center">
  <thead>
    <tr class="text-center items-center">
      <th class="w-2/6">Company</th>
      <th class="w-1/6">Cost</th>
      <th class="w-1/6">Payment Date</th>
      <th class="w-1/6">Liquidity</th>
      <th class="w-1/6">Cancel Contract</th>
    </tr>
  </thead>
  <tbody>
    <tr v-for="upcoming in data" :key="upcoming">
      <td>{{upcoming.client}}</td>
      <td>{{upcoming.amount}} Eth</td>
      <td>{{upcoming.date}}</td>
      <td v-if="upcoming.amount <= bing" class="bg-green-100">Able to Honor</td>
      <td v-else class="bg-red-300 animate-pulse">Unable to Honor</td>
      <td class="flex flex-col items-center"><div>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
</svg></div></td>
    </tr>
  </tbody>
</table>
<ul v-else class="flex justify-center">
<div class="loadingio-spinner-rolling-dd5e02hqvg9"><div class="ldio-xvobpw7hude">
<div></div>
</div></div>
</ul>
              </div>
      </div>
</template>

<script>
import axios from 'axios'
import moralis from 'moralis'
export default {
data(){
  return{
    data: '',
    bing: 1
  }
},
async mounted(){
  let user = await moralis.User.current().get("ethAddress")
  const options = { chain: "ropsten", address: user, from_block: "0"};
await moralis.Web3API.account.getNativeBalance(options).then(async (res) => {
  this.bing = await res.balance/1000000000000000000
});
      await  axios.post('http://localhost:3000/active', 
{
    "wallet": user
}).then(async (res) =>{
  this.data = await res.data
})
}
}
</script>

<style>
.custom-height{
  height: 27rem;
}
@keyframes ldio-xvobpw7hude {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-xvobpw7hude div {
  position: absolute;
  width: 50px;
  height: 50px;
  border: 5px solid #ff9b71;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-xvobpw7hude div {
  animation: ldio-xvobpw7hude 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-dd5e02hqvg9 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-xvobpw7hude {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
}
.ldio-xvobpw7hude div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>